version: '3.2'

services:

  backend_alendre:
    build: backend_alendre
    container_name: backend_alendre
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend_ecommerce:
    build: backend_ecommerce
    container_name: backend_ecommerce
    ports:
      - 20160:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend_ecommerce_employees:
    build: backend_ecommerce_employees
    container_name: backend_ecommerce_employees
    ports:
      - 20240:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend_ecommerce_partners:
    build: backend_ecommerce_partners
    container_name: backend_ecommerce_partners
    ports:
      - 20320:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  frontend_alendre:
    build: frontend_alendre
    container_name: frontend_alendre
    ports:
      - 20400:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  frontend_atelier:
    build: frontend_atelier
    container_name: frontend_atelier
    ports:
      - 20480:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  frontend_ecommerce:
    build: frontend_ecommerce
    container_name: frontend_ecommerce
    ports:
      - 20540:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=verysecret
  #     - MYSQL_DATABASE=yii2advanced
  #     - MYSQL_USER=yii2advanced
  #     - MYSQL_PASSWORD=secret

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret
networks:
  default:
    name: alendre_mysql